version: '3'
services:
  node-server:
    container_name: node
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=clinic
      - DB_PORT=3306
    depends_on:
      - db  # ✅ ให้ Node รอ MySQL พร้อมก่อนเริ่มทำงาน

  db:
    image: mysql:latest
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
